### ISSUE TITLE
Handle commands from Admin

### ISSUE THREAD

**Issue by Katreque** [Katreque/bottotherobot#8]
Create a command handler to the bot.

- Check the bot prefix in the .env.
- Detect the bot commands.
- Only execute commands if the user has admin privileges.

**Comment by Katreque** [comment]
Reference: https://discordjs.guide/command-handling

**Comment by InternetRamen** [comment]
I'm down to do this :)

**Comment by InternetRamen** [comment]
#12

**Comment by Katreque** [comment]
Thanks for the PR @InternetRamen. :) 

We don't want to import the functionalities through file reading. The handlers should detect the command and its args and use CommonJS modules to call the right methods.
